# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html

fos_rest:
    body_listener: true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
    param_fetcher_listener: true
    allowed_methods_listener:  true
    exception:
        codes:
            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': 404
        messages:
            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': true
