doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        schema_filter: "/^storage_api__/"
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            
            Fixtures:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/DataFixtures/Entity'
                prefix: 'App\DataFixtures\Entity'
                alias: Fixtures
