vich_uploader:
    db_driver: orm

    mappings:
        uploaded_files:
            uri_prefix: /file
            upload_destination: '%kernel.project_dir%/public/files'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
